## Testing Air Quality (Namely PM)

In [3]:
## testing pm10

import pandas as pd
data = pd.read_csv('air quality data.csv')
sortedData=data.sort_values(by=['pm10','pm10b'])
sortedData.head(25)

/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (4,8,10,14,16,18,20,22,28,30,32,34,36,38,40,42,44,46,48,50,56,58,60,62,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,site,datetime,stat,bcstat,bcstat_txt,bp,bp_txt,co,co_txt,h2s,...,sonicws,sonicws_txt,uvpm,uvpm_txt,rainfall,rainfall_txt,solarrad,solarrad_txt,uv_rad,uv_rad_txt
18239,Lincoln,2017-09-23T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41574,Flag Plaza,2017-09-23T00:00:00,Min,NaN,NaN,NaN,NaN,0.3000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13286,Lincoln,2016-07-05T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21224,Lincoln,2016-11-07T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111525,Flag Plaza,2019-07-22T00:00:00,Min,NaN,NaN,NaN,NaN,0.1576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20709,Liberty 2,2016-10-07T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60675,Flag Plaza,2018-06-24T00:00:00,Min,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106569,Flag Plaza,2019-05-24T00:00:00,Min,NaN,NaN,NaN,NaN,0.0000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10703,Flag Plaza,2016-06-03T00:00:00,Min,NaN,NaN,NaN,NaN,0.2000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11336,Liberty 2,2016-06-12T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17923,Liberty 2,2016-08-30T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22337,Flag Plaza,2016-11-19T00:00:00,Min,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46154,Liberty 2,2017-11-06T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59307,Flag Plaza,2018-06-05T00:00:00,Min,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106611,Lincoln,2019-05-24T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107997,Flag Plaza,2019-06-10T00:00:00,Min,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4436,Liberty 2,2016-03-10T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12874,Flag Plaza,2016-07-07T00:00:00,Min,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17659,Flag Plaza,2016-09-25T00:00:00,Min,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17719,Glassport High Street,2016-09-11T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18192,Lincoln,2016-09-20T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22254,Liberty 2,2016-10-26T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35694,Flag Plaza,2017-07-29T00:00:00,Min,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35906,Flag Plaza,2017-06-25T00:00:00,Min,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36390,Glassport High Street,2017-10-23T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
##testing pm25

import pandas as pd
data = pd.read_csv('air quality data.csv')
sortedData=data.sort_values(by=['pm25','pm25b'])
sortedData.head(25)

/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (4,8,10,14,16,18,20,22,28,30,32,34,36,38,40,42,44,46,48,50,56,58,60,62,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,site,datetime,stat,bcstat,bcstat_txt,bp,bp_txt,co,co_txt,h2s,...,sonicws,sonicws_txt,uvpm,uvpm_txt,rainfall,rainfall_txt,solarrad,solarrad_txt,uv_rad,uv_rad_txt
106359,Lincoln,2019-05-21T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2453,Lincoln,2016-02-16T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4340,Lincoln,2016-03-18T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5146,Liberty 2,2016-03-18T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12778,Liberty 2,2016-06-28T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12789,Liberty 2,2016-06-27T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18618,Lincoln,2016-10-11T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20010,Lincoln,2016-11-09T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23508,Liberty 2,2016-11-19T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35519,Liberty 2,2017-06-06T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38277,Liberty 2,2017-09-01T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39527,Lincoln,2017-08-08T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39540,Liberty 2,2017-10-12T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42591,Lincoln,2017-10-09T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44824,Liberty 2,2017-10-13T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45649,Liberty 2,2017-10-23T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45723,Liberty 2,2017-11-19T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46003,Lincoln,2017-10-23T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46362,Liberty 2,2017-12-25T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47055,Lincoln,2017-11-29T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48132,Liberty 2,2018-01-14T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49074,Liberty 2,2017-12-23T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50792,Lincoln,2018-01-12T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54273,Liberty 2,2018-03-19T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56151,Liberty 2,2018-04-15T00:00:00,Min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN